name: MSBuild

on: [push, pull_request]

env:
  SOLUTION_NAME: ScreenRecorderLib
  PROJECT_NAME: TestApp

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: nuget restore ${{ env.SOLUTION_NAME }}.sln
    - uses: microsoft/setup-msbuild@v1
    - run: msbuild /m '/p:Configuration=Release;Platform=${{ env.BUILD_PLATFORM }}' ${{ env.SOLUTION_NAME }}.sln
    # Save artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.SOLUTION_NAME }}-${{ github.sha }}
        path: ${{ env.PROJECT_NAME }}\bin\${{ env.BUILD_PLATFORM }}\Release
