name: MSBuild

on: [push, pull_request]

env:
  SOLUTION_NAME: ScreenRecorderLib
  PROJECT_NAME: TestApp

jobs:
  build:
    name: Build for solution platform ${{ matrix.platform }}
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, x86]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - run: nuget restore ${{ env.SOLUTION_NAME }}.sln
    - run: msbuild /m '/p:Configuration=Release;Platform="${{ matrix.platform }}"' ${{ env.SOLUTION_NAME }}.sln
    # Save artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.SOLUTION_NAME }}-${{ github.sha }}
        path: ${{ env.PROJECT_NAME }}\bin\${{ matrix.platform }}\Release
